// UNICO ARQUIVO PARA EDITAR CONTEUDO -- versao bilingue (PT/EN).
// Estrutura: I18N.pt e I18N.en tem exatamente os mesmos campos.
// Campos ainda [preencher: ...] / [fill in: ...] sao dados que a Mariana
// nao informou -- nada foi inventado alem disso.

const I18N = {
  pt: {
    site: {
      nome: "Mariana Pinto",
      cargoLocal: "Product Designer — Recife, Brasil",
      linkedin: "https://www.linkedin.com/in/marianapintodesigner/",
      whatsapp: "https://wa.me/5581999642055",
      email: "[preencher: seu e-mail]",
      resume: "[preencher: link do currículo — PDF ou Google Drive]",
    },
    hero: {
      status: "aberta a oportunidades remotas ou híbridas",
      headline: "Olá, aqui é Mariana.",
      atualmente: "Product Designer @ SIEG",
      entregando: "Design Systems, Discovery e decisões orientadas por dados",
    },
    about: {
      headline: "Acredito que um bom design não começa na interface. Começa entendendo o problema certo para resolver.",
      paragrafos: [
        "Sou Product Designer com experiência na evolução de produtos SaaS B2B, atuando desde a descoberta do problema até a implementação das soluções em produção.",
        "Trabalho de forma colaborativa com Product Managers, Engenharia e stakeholders para transformar problemas complexos em soluções simples, escaláveis e centradas no usuário.",
        "Gosto de entrar em produtos que ainda não têm padrão nenhum — foi assim que propus e liderei a criação do primeiro Design System da empresa, e depois ajudei a estruturar como o time passou a medir satisfação do usuário de forma consistente.",
        "Atualmente estou aprofundando meus conhecimentos em liderança, estratégia de produto e Product Analytics para ampliar meu impacto na construção de produtos digitais.",
      ],
      principios: [
        { titulo: "Não penso em telas.", descricao: "Penso em problemas antes de desenhar soluções." },
        { titulo: "Design é colaboração.", descricao: "As melhores soluções surgem da parceria entre Produto, Engenharia e Design." },
        { titulo: "Escalabilidade importa.", descricao: "Construo soluções que possam evoluir de forma consistente ao longo do tempo." },
        { titulo: "Dados orientam decisões.", descricao: "Pesquisa e feedback dos usuários reduzem incertezas e fortalecem decisões de produto." },
      ],
    },
    contact: {
      headline: "Sempre aberta para conversar sobre Produto, Design Systems e oportunidades para construir produtos digitais de impacto.",
      botao: "Vamos conversar",
    },
    casesSectionHeadline: "Projetos que mostram como transformo problemas em decisões de produto.",
    ui: {
      nav: { cases: "cases", sobre: "sobre", contato: "contato", curriculo: "currículo" },
      footer: { local: "Recife, Brasil" },
      misc: {
        verCases: "Ver cases",
        verCaseCompleto: "ver case completo →",
        proximoCase: "próximo case",
        todosOsCases: "← todos os cases",
        printFigma: "print do Figma aqui",
      },
      aria: { linkedin: "LinkedIn", whatsapp: "WhatsApp", tema: "Alternar tema", menu: "Abrir menu", idioma: "Mudar idioma" },
    },
    caseLabels: {
      problema: "problema",
      contexto: "contexto",
      desafio: "o desafio",
      objetivos: "objetivos",
      meuPapel: "meu papel",
      hipoteses: "hipóteses",
      discovery: "discovery",
      pesquisa: "pesquisa",
      insights: "principais insights",
      estrategia: "estratégia de design",
      processo: "processo",
      tradeoffs: "decisão de produto",
      decisao: "decisão",
      prototipacao: "exploração",
      solucao: "solução",
      componentLibrary: "component library",
      colaboracao: "colaboração",
      validacao: "validação",
      handoff: "handoff",
      resultado: "resultado",
      aprendizados: "aprendizados",
      fechamento: "reflexão final",
      proximosPassos: "próximos passos",
      empresa: "empresa",
      squad: "squad",
      papel: "papel",
      periodo: "período",
      ferramentas: "ferramentas",
    },
    cases: [
      {
        slug: "design-system-sieg",
        title: "Construindo o primeiro Design System da empresa",
        tags: ["Design System", "Governança"],
        oneLiner: "A empresa não tinha nenhum padrão entre squads. Levei a ideia, construí do zero e defini a governança inicial.",
        meta: {
          empresa: "SIEG",
          squad: "Todos os squads de produto",
          papel: "Idealizadora e responsável pela criação inicial",
          periodo: "[preencher: período]",
          stack: "Figma, Storybook",
        },
        contexto: "A SIEG não tinha um Design System. Cada squad construía suas próprias soluções de interface, sem um padrão visual ou de componentes compartilhado entre os produtos.",
        problema: "Falta de consistência e padrão entre os produtos, gerando retrabalho e custo no dia a dia de design e desenvolvimento.",
        papel: "Propus a ideia de um Design System para a empresa, que aprovou o projeto. Conduzi a criação do zero — tokens, estilos, componentes e variantes — e defini a governança inicial de criação, revisão e evolução dos componentes.",
        discovery: "A necessidade foi identificada a partir do uso diário dos produtos e da percepção recorrente de retrabalho e custo entre os squads — não de uma pesquisa formal, mas de um problema que se repetia toda semana.",
        pesquisa: "[preencher: pesquisa/benchmark realizado nesta fase, se houve]",
        hipoteses: ["[preencher: hipótese 1]"],
        processo: "Proposta e aprovação do projeto pela empresa, criação de tokens, estilos, componentes e variantes do zero, definição da governança inicial de criação e revisão, documentação em Figma e Storybook, e adoção pelos squads.",
        decisoes: [
          { titulo: "Construir do zero, sem herdar nenhum padrão anterior", descricao: "Toda a base visual e de componentes foi criada nesta iniciativa — não havia nada prévio para adaptar." },
          { titulo: "Definir governança já na primeira fase", descricao: "O processo de criação, revisão e evolução dos componentes foi definido desde o início. Mais de um ano depois, essa governança evoluiu bastante e hoje está sob responsabilidade de outros designers do time." },
        ],
        tradeoffs: [{ escolha: "[preencher: escolha]", custo: "[preencher: custo]" }],
        prototipacao: "[preencher: prototipação]",
        validacao: "Adoção alta por parte do time de desenvolvimento e maior facilidade para construir e ajustar as ferramentas do produto — hoje o sistema tem 317 componentes, usados por todos os designers e desenvolvedores da empresa.",
        handoff: "Documentação em Figma e Storybook, permitindo que os times de desenvolvimento consumissem os componentes diretamente.",
        resultados: [
          "317 componentes documentados, usados por todos os designers e desenvolvedores da empresa.",
          "Redução de custo e retrabalho, com melhoria na qualidade dos produtos construídos a partir do sistema.",
        ],
        aprendizados: ["Depois de mais de um ano, a governança do Design System passou para outros designers do time — iniciar um projeto e depois passar a liderança adiante também faz parte do ciclo de maturidade de um sistema."],
        proximosPassos: ["[preencher: próximo passo 1]"],
        imagens: [
          { label: "[preencher]", descricao: "[preencher: ex. print da biblioteca de componentes no Figma]" },
          { label: "[preencher]", descricao: "[preencher: ex. estrutura de tokens]" },
          { label: "[preencher]", descricao: "[preencher: ex. documentação no Storybook]" },
        ],
      },
      {
        slug: "csat-produto",
        title: "Como estruturamos uma estratégia de CSAT para apoiar decisões de Produto",
        tags: ["CSAT", "Pesquisa de produto"],
        oneLiner: "A SIEG não tinha métricas de produto. Criei, com o PO, a regra de pesquisa de CSAT por módulo.",
        meta: {
          empresa: "SIEG",
          squad: "Pesquisa & Produto",
          papel: "Criação da regra de disparo em parceria com o PO",
          periodo: "[preencher: período]",
          stack: "Indecx",
        },
        contexto: "A SIEG não tinha métricas de produto estruturadas. Medir satisfação do usuário virou meta do setor, diante da necessidade de decisões mais orientadas por dado.",
        problema: "Faltavam dados de produto para embasar decisões de forma consistente.",
        papel: "Criei, em parceria com o PO, a regra de pesquisa de CSAT para cada módulo do produto.",
        discovery: "A necessidade surgiu como meta do setor e da falta de dados direcionados para embasar decisões de produto.",
        pesquisa: "[preencher: pesquisa]",
        hipoteses: ["[preencher: hipótese 1]"],
        processo: "Definição da regra de disparo de CSAT por módulo em parceria com o PO, implementação na plataforma Indecx e acompanhamento contínuo dos dados coletados.",
        decisoes: [{ titulo: "Medir por módulo do produto, não o produto como um todo", descricao: "Cada módulo passou a ter sua própria regra de pesquisa, em vez de uma medição única e genérica." }],
        tradeoffs: [{ escolha: "[preencher: escolha]", custo: "[preencher: custo]" }],
        prototipacao: "[preencher: prototipação]",
        validacao: "Validação pelo volume de respostas recebidas até o momento — o projeto ainda está em fase de teste.",
        handoff: "Implementação e configuração diretamente na plataforma Indecx, com acompanhamento contínuo junto ao PO.",
        resultados: [
          "Dados de produto passaram a existir onde antes não havia nenhum.",
          "Base inicial para decisões mais assertivas de produto, ainda em fase de teste e evolução.",
        ],
        aprendizados: ["[preencher: aprendizado 1]"],
        proximosPassos: ["Ampliar a análise dos dados à medida que o volume de respostas cresce."],
        imagens: [
          { label: "[preencher]", descricao: "[preencher: ex. print da configuração no Indecx]" },
          { label: "[preencher]", descricao: "[preencher: ex. regra de disparo por módulo]" },
          { label: "[preencher]", descricao: "[preencher: ex. dashboard de respostas]" },
        ],
      },
      {
        slug: "controle-pendencias",
        title: "Evoluindo uma funcionalidade crítica através de Discovery e colaboração multidisciplinar",
        tags: ["Discovery", "Colaboração multidisciplinar"],
        oneLiner: "[preencher: resumo de 1 linha do case]",
        meta: {
          empresa: "SIEG",
          squad: "[preencher: squad]",
          papel: "[preencher: seu papel no projeto]",
          periodo: "[preencher: período]",
          stack: "[preencher: ferramentas usadas]",
        },
        problema: "[preencher: problema]",
        contexto: "[preencher: contexto]",
        papel: "[preencher: seu papel]",
        hipoteses: ["[preencher: hipótese 1]"],
        discovery: "[preencher: discovery]",
        pesquisa: "[preencher: pesquisa]",
        processo: "[preencher: processo]",
        tradeoffs: [{ escolha: "[preencher: escolha]", custo: "[preencher: custo]" }],
        decisoes: [{ titulo: "[preencher: decisão 1]", descricao: "[preencher: descrição]" }],
        prototipacao: "[preencher: prototipação]",
        validacao: "[preencher: validação]",
        handoff: "[preencher: handoff]",
        resultados: ["[preencher: resultado 1]"],
        aprendizados: ["[preencher: aprendizado 1]"],
        proximosPassos: ["[preencher: próximo passo 1]"],
        imagens: [
          { label: "[preencher]", descricao: "[preencher: o que essa imagem deve mostrar]" },
          { label: "[preencher]", descricao: "[preencher: o que essa imagem deve mostrar]" },
          { label: "[preencher]", descricao: "[preencher: o que essa imagem deve mostrar]" },
        ],
      },
      {
        slug: "refatoracao-sieg-iris",
        title: "Rebranding e Refatoração do SIEG IriS",
        capa: "images/iris-cover.png",
        tags: ["Product Design", "SaaS B2B", "Discovery", "UX Research", "Interface Design", "Component Library", "Design Foundation", "Product Strategy"],
        oneLiner: "Como transformamos um produto SaaS legado em uma experiência mais intuitiva, consistente e preparada para escalar.",
        meta: {
          empresa: "SIEG",
          squad: "Íris",
          papel: "Product Designer",
          periodo: "6 meses",
          stack: "Figma, Notion",
        },
        contexto: [
          "O SIEG IriS é um produto SaaS utilizado por escritórios contábeis para monitoramento e gestão de pendências fiscais.",
          "Após anos de evolução, o sistema passou a apresentar inconsistências visuais, fluxos fragmentados e diferentes padrões de interface entre módulos, tornando a experiência menos intuitiva e aumentando o esforço necessário para executar tarefas do dia a dia.",
          "Além da atualização visual da marca, surgiu a oportunidade de repensar a experiência do produto de forma mais ampla, equilibrando necessidades dos usuários, objetivos do negócio e viabilidade técnica.",
        ],
        desafio: [
          "O desafio não era apenas modernizar a interface. Precisávamos reorganizar fluxos complexos, reduzir a carga cognitiva dos usuários e criar uma experiência mais consistente sem comprometer a rotina de profissionais que utilizavam diariamente o sistema para processos fiscais.",
          "Ao mesmo tempo, a solução precisava estabelecer padrões reutilizáveis que facilitassem futuras evoluções do produto.",
        ],
        objetivos: [
          "Simplificar fluxos críticos de navegação.",
          "Melhorar a organização das informações.",
          "Reduzir inconsistências entre diferentes módulos.",
          "Modernizar a identidade visual do produto.",
          "Criar uma base reutilizável para futuras evoluções da interface.",
        ],
        problema: "Funcionalidades essenciais estavam enterradas sob camadas de informação desnecessárias. Isso gerava baixa adoção do sistema e frustração dos usuários — o problema não era estético, era estrutural.",
        papel: [
          "Conduzir o processo de Discovery em parceria com Produto.",
          "Mapear dores e oportunidades por meio de pesquisas com usuários.",
          "Estruturar novos fluxos de navegação.",
          "Redesenhar a interface considerando usabilidade e consistência.",
          "Construir uma biblioteca inicial de componentes no Figma para apoiar a padronização das interfaces.",
          "Acompanhar a evolução das soluções durante o desenvolvimento.",
        ],
        discovery: [
          "Antes de iniciar qualquer proposta visual, buscamos compreender como os usuários utilizavam o sistema e quais eram as principais dificuldades encontradas durante a execução das tarefas.",
          "O Discovery foi conduzido por meio de entrevistas, análise da jornada, benchmark e organização das informações utilizando Card Sorting.",
          "Esse processo permitiu identificar oportunidades que orientaram todas as decisões de Design ao longo do projeto.",
        ],
        pesquisa: "Entrevistas com usuários, análise de jornada, benchmark e Card Sorting para reorganizar a estrutura de informações do sistema.",
        insights: [
          "Navegação excessivamente complexa para tarefas frequentes.",
          "Grande volume de informações competindo pela atenção do usuário.",
          "Inconsistência entre componentes e padrões visuais.",
          "Fluxos diferentes para tarefas semelhantes.",
          "Curva de aprendizado elevada para novos usuários.",
        ],
        hipoteses: [
          "Se reorganizássemos os menus e reduzíssemos a quantidade de informação exposta de uma vez, a usabilidade do sistema melhoraria.",
          "Se aplicássemos consistência visual em toda a interface, isso aumentaria a percepção de qualidade e confiança dos usuários no sistema.",
        ],
        estrategia: [
          { titulo: "Simplificar", descricao: "Reduzir etapas e tornar os principais fluxos mais diretos." },
          { titulo: "Organizar", descricao: "Melhorar a hierarquia das informações para facilitar a tomada de decisão." },
          { titulo: "Padronizar", descricao: "Criar padrões reutilizáveis que aumentassem a consistência entre diferentes áreas do produto." },
          { titulo: "Preparar para escalar", descricao: "Estruturar uma base que permitisse evoluir a interface de maneira mais eficiente ao longo do tempo." },
        ],
        tradeoffs: [{ titulo: "Modernização × Continuidade da experiência", descricao: "Durante a refatoração, um dos principais desafios foi modernizar a interface sem comprometer a familiaridade dos usuários com o produto. Optamos por preservar padrões já consolidados nos fluxos mais críticos, enquanto reorganizávamos a arquitetura da informação, a hierarquia visual e os componentes da interface. Essa decisão permitiu evoluir a experiência de forma gradual, reduzindo a curva de aprendizado e facilitando a adoção das mudanças." }],
        decisoes: [],
        prototipacao: [
          "A partir dos aprendizados do Discovery foram exploradas diferentes alternativas de navegação, organização das informações e estrutura das páginas.",
          "Os wireframes permitiram validar hipóteses antes da evolução visual da interface, reduzindo retrabalho e alinhando expectativas entre Produto, Design e Engenharia.",
        ],
        solucao: {
          intro: "A solução consistiu na reorganização completa da arquitetura das principais telas do produto. Entre as principais mudanças estavam:",
          itens: [
            "reorganização dos dashboards",
            "simplificação da navegação",
            "revisão da hierarquia visual",
            "padronização de componentes",
            "melhoria dos filtros e tabelas",
            "maior clareza na apresentação das informações",
          ],
          fechamento: "O objetivo foi reduzir a carga cognitiva dos usuários e tornar a execução das tarefas mais eficiente.",
        },
        componentLibrary: [
          "Durante o projeto percebemos que diversos elementos da interface estavam sendo recriados constantemente, dificultando a manutenção e comprometendo a consistência visual do produto.",
          "Como resposta imediata, estruturamos uma biblioteca de componentes no Figma, reunindo padrões de cores, tipografia, botões, inputs, ícones e demais elementos reutilizáveis.",
          "Embora ainda não fosse um Design System completo, essa iniciativa representou um importante avanço na maturidade do Design dentro da empresa. Ela permitiu validar padrões, reduzir inconsistências e demonstrou a necessidade de evoluir para um Design System estruturado, iniciativa que seria desenvolvida posteriormente.",
          "Esse projeto foi o primeiro passo para a construção do Design System oficial da SIEG.",
        ],
        colaboracao: "O projeto foi desenvolvido em colaboração constante com Produto e Engenharia. As decisões eram discutidas ao longo do processo para equilibrar necessidades dos usuários, objetivos do negócio e viabilidade técnica, reduzindo riscos durante a implementação.",
        validacao: "",
        handoff: "",
        resultados: [
          "Navegação mais simples e intuitiva.",
          "Interface visualmente mais consistente.",
          "Melhor organização das informações.",
          "Redução da complexidade dos fluxos.",
          "Base reutilizável para evolução contínua do produto.",
          "Feedback positivo dos usuários durante as validações realizadas.",
        ],
        resultadosNota: "Observação: como não possuímos métricas quantitativas consolidadas desse projeto, optei por apresentar apenas resultados que podem ser sustentados pela experiência real, sem usar números sem comprovação.",
        aprendizados: [
          "Esse projeto reforçou que uma refatoração vai muito além de uma atualização visual. Ao compreender profundamente o contexto dos usuários e estruturar decisões de forma colaborativa, foi possível criar uma experiência mais consistente e preparar o produto para evoluções futuras.",
          "Também foi durante esse projeto que percebemos a importância de padronizar componentes e criar uma linguagem comum entre Design e Desenvolvimento — aprendizado que influenciou diretamente a criação do Design System oficial da empresa.",
        ],
        fechamento: "Mais do que redesenhar interfaces, esse projeto marcou uma mudança na forma como o Design passou a ser pensado dentro da empresa. A criação da biblioteca de componentes evidenciou a necessidade de uma estrutura mais escalável, servindo como ponto de partida para o Design System oficial desenvolvido posteriormente.",
        proximosPassos: ["A refatoração do IriS evidenciou a necessidade de padrões mais consistentes entre Design e Desenvolvimento. A biblioteca de componentes criada durante o projeto serviu como base para a construção do DSI, o Design System oficial da SIEG."],
        imagens: [
          { label: "Antes da refatoração", descricao: "Tela original do Íris — menus e informações sobrecarregadas", src: "images/iris-01-antes.png" },
          { label: "Fluxograma de pesquisa", descricao: "Pesquisa → Mapeamento da Jornada → Análise de Dados → Benchmark", src: "images/iris-02-fluxograma.png" },
          { label: "Component Library do Íris", descricao: "Paleta de cores, tipografia e componentes (botões, inputs, ícones)", src: "images/iris-04-component-library.png" },
          { label: "Wireframes", descricao: "Estrutura de baixa fidelidade validando a nova navegação", src: "images/iris-03-wireframes.png" },
          { label: "Depois da refatoração", descricao: "Dashboard final — Novo SIEG Íris", src: "images/iris-05-depois.png" },
        ],
      },
    ],
  },

  en: {
    site: {
      nome: "Mariana Pinto",
      cargoLocal: "Product Designer — Recife, Brazil",
      linkedin: "https://www.linkedin.com/in/marianapintodesigner/",
      whatsapp: "https://wa.me/5581999642055",
      email: "[fill in: your email]",
      resume: "[fill in: resume link — PDF or Google Drive]",
    },
    hero: {
      status: "open to remote or hybrid opportunities",
      headline: "Hi, this is Mariana.",
      atualmente: "Product Designer @ SIEG",
      entregando: "Design Systems, Discovery, and data-informed decisions",
    },
    about: {
      headline: "I believe good design doesn't start on the screen. It starts with understanding the right problem to solve.",
      paragrafos: [
        "I'm a Product Designer with experience evolving B2B SaaS products, working from problem discovery all the way through shipping solutions to production.",
        "I work collaboratively with Product Managers, Engineering, and stakeholders to turn complex problems into simple, scalable, user-centered solutions.",
        "I like stepping into products that don't have any standard yet — that's how I proposed and led the creation of the company's first Design System, and later helped structure how the team started measuring user satisfaction consistently.",
        "I'm currently deepening my knowledge in leadership, product strategy, and Product Analytics to grow my impact on building digital products.",
      ],
      principios: [
        { titulo: "I don't think in screens.", descricao: "I think in problems before designing solutions." },
        { titulo: "Design is collaboration.", descricao: "The best solutions come from partnership between Product, Engineering, and Design." },
        { titulo: "Scalability matters.", descricao: "I build solutions that can evolve consistently over time." },
        { titulo: "Data drives decisions.", descricao: "Research and user feedback reduce uncertainty and strengthen product decisions." },
      ],
    },
    contact: {
      headline: "Always open to talk about Product, Design Systems, and opportunities to build impactful digital products.",
      botao: "Let's talk",
    },
    casesSectionHeadline: "Projects that show how I turn problems into product decisions.",
    ui: {
      nav: { cases: "cases", sobre: "about", contato: "contact", curriculo: "resume" },
      footer: { local: "Recife, Brazil" },
      misc: {
        verCases: "View cases",
        verCaseCompleto: "view full case →",
        proximoCase: "next case",
        todosOsCases: "← all cases",
        printFigma: "Figma screenshot here",
      },
      aria: { linkedin: "LinkedIn", whatsapp: "WhatsApp", tema: "Toggle theme", menu: "Open menu", idioma: "Switch language" },
    },
    caseLabels: {
      problema: "problem",
      contexto: "context",
      desafio: "the challenge",
      objetivos: "objectives",
      meuPapel: "my role",
      hipoteses: "hypotheses",
      discovery: "discovery",
      pesquisa: "research",
      insights: "key insights",
      estrategia: "design strategy",
      processo: "process",
      tradeoffs: "product decision",
      decisao: "decision",
      prototipacao: "exploration",
      solucao: "solution",
      componentLibrary: "component library",
      colaboracao: "collaboration",
      validacao: "validation",
      handoff: "handoff",
      resultado: "results",
      aprendizados: "learnings",
      fechamento: "closing reflection",
      proximosPassos: "next steps",
      empresa: "company",
      squad: "squad",
      papel: "role",
      periodo: "duration",
      ferramentas: "tools",
    },
    cases: [
      {
        slug: "design-system-sieg",
        title: "Building the company's first Design System",
        tags: ["Design System", "Governance"],
        oneLiner: "The company had no standard across squads. I proposed the idea, built it from scratch, and defined the initial governance.",
        meta: {
          empresa: "SIEG",
          squad: "All product squads",
          papel: "Originator and lead of the initial build",
          periodo: "[fill in: duration]",
          stack: "Figma, Storybook",
        },
        contexto: "SIEG had no Design System. Each squad built its own interface solutions, with no shared visual or component standard across products.",
        problema: "Lack of consistency and standards across products, creating rework and cost in day-to-day design and development.",
        papel: "I proposed the idea of a Design System to the company, which approved the project. I led the build from scratch — tokens, styles, components, and variants — and defined the initial governance for creating, reviewing, and evolving components.",
        discovery: "The need was identified through daily product usage and a recurring sense of rework and cost across squads — not from formal research, but from a problem that kept repeating every week.",
        pesquisa: "[fill in: research/benchmark done at this stage, if any]",
        hipoteses: ["[fill in: hypothesis 1]"],
        processo: "Proposal and approval by the company, creation of tokens, styles, components, and variants from scratch, definition of initial creation/review governance, documentation in Figma and Storybook, and adoption across squads.",
        decisoes: [
          { titulo: "Build from scratch, without inheriting any prior standard", descricao: "The entire visual and component foundation was created in this initiative — there was nothing prior to adapt." },
          { titulo: "Define governance in the first phase", descricao: "The process for creating, reviewing, and evolving components was defined from the start. More than a year later, that governance has evolved significantly and is now owned by other designers on the team." },
        ],
        tradeoffs: [{ escolha: "[fill in: trade-off choice]", custo: "[fill in: cost]" }],
        prototipacao: "[fill in: prototyping]",
        validacao: "High adoption from the development team and greater ease building and adjusting the product's tools — the system now has 317 components, used by every designer and developer at the company.",
        handoff: "Documentation in Figma and Storybook, letting development teams consume components directly.",
        resultados: [
          "317 components documented, used by every designer and developer at the company.",
          "Reduced cost and rework, with improved quality across products built from the system.",
        ],
        aprendizados: ["After more than a year, Design System governance moved to other designers on the team — starting a project and later handing off leadership is also part of a system's maturity cycle."],
        proximosPassos: ["[fill in: next step]"],
        imagens: [
          { label: "[fill in]", descricao: "[fill in: e.g. screenshot of the component library in Figma]" },
          { label: "[fill in]", descricao: "[fill in: e.g. token structure]" },
          { label: "[fill in]", descricao: "[fill in: e.g. Storybook documentation]" },
        ],
      },
      {
        slug: "csat-produto",
        title: "How we structured a CSAT strategy to support Product decisions",
        tags: ["CSAT", "Product research"],
        oneLiner: "SIEG had no product metrics. I created the per-module CSAT survey rule together with the PO.",
        meta: {
          empresa: "SIEG",
          squad: "Research & Product",
          papel: "Created the trigger rule in partnership with the PO",
          periodo: "[fill in: duration]",
          stack: "Indecx",
        },
        contexto: "SIEG had no structured product metrics. Measuring user satisfaction became a department goal, given the need for more data-informed decisions.",
        problema: "There was no product data to consistently inform decisions.",
        papel: "I created, in partnership with the PO, the CSAT survey rule for each product module.",
        discovery: "The need emerged as a department goal and from the lack of targeted data to inform product decisions.",
        pesquisa: "[fill in: research]",
        hipoteses: ["[fill in: hypothesis 1]"],
        processo: "Definition of the per-module CSAT trigger rule in partnership with the PO, implementation on the Indecx platform, and ongoing monitoring of the collected data.",
        decisoes: [{ titulo: "Measure per product module, not the product as a whole", descricao: "Each module got its own survey rule, instead of a single generic measurement." }],
        tradeoffs: [{ escolha: "[fill in: trade-off choice]", custo: "[fill in: cost]" }],
        prototipacao: "[fill in: prototyping]",
        validacao: "Validated by the volume of responses received so far — the project is still in a test phase.",
        handoff: "Implementation and configuration directly on the Indecx platform, with ongoing follow-up alongside the PO.",
        resultados: [
          "Product data started to exist where there was none before.",
          "An initial foundation for more assertive product decisions, still in test and evolution phase.",
        ],
        aprendizados: ["[fill in: learning 1]"],
        proximosPassos: ["Expand the data analysis as response volume grows."],
        imagens: [
          { label: "[fill in]", descricao: "[fill in: e.g. screenshot of the Indecx configuration]" },
          { label: "[fill in]", descricao: "[fill in: e.g. per-module trigger rule]" },
          { label: "[fill in]", descricao: "[fill in: e.g. response dashboard]" },
        ],
      },
      {
        slug: "controle-pendencias",
        title: "Evolving a critical feature through Discovery and cross-functional collaboration",
        tags: ["Discovery", "Cross-functional collaboration"],
        oneLiner: "[fill in: one-line summary of the case]",
        meta: {
          empresa: "SIEG",
          squad: "[fill in: squad]",
          papel: "[fill in: your role in the project]",
          periodo: "[fill in: duration]",
          stack: "[fill in: tools used]",
        },
        problema: "[fill in: problem]",
        contexto: "[fill in: context]",
        papel: "[fill in: your role]",
        hipoteses: ["[fill in: hypothesis 1]"],
        discovery: "[fill in: discovery]",
        pesquisa: "[fill in: research]",
        processo: "[fill in: process]",
        tradeoffs: [{ escolha: "[fill in: trade-off choice]", custo: "[fill in: cost]" }],
        decisoes: [{ titulo: "[fill in: decision 1]", descricao: "[fill in: description]" }],
        prototipacao: "[fill in: prototyping]",
        validacao: "[fill in: validation]",
        handoff: "[fill in: handoff]",
        resultados: ["[fill in: result 1]"],
        aprendizados: ["[fill in: learning 1]"],
        proximosPassos: ["[fill in: next step 1]"],
        imagens: [
          { label: "[fill in]", descricao: "[fill in: what this image should show]" },
          { label: "[fill in]", descricao: "[fill in: what this image should show]" },
          { label: "[fill in]", descricao: "[fill in: what this image should show]" },
        ],
      },
      {
        slug: "refatoracao-sieg-iris",
        title: "Rebranding and Refactoring SIEG IriS",
        capa: "images/iris-cover.png",
        tags: ["Product Design", "SaaS B2B", "Discovery", "UX Research", "Interface Design", "Component Library", "Design Foundation", "Product Strategy"],
        oneLiner: "How we turned a legacy SaaS product into a more intuitive, consistent experience built to scale.",
        meta: {
          empresa: "SIEG",
          squad: "Íris",
          papel: "Product Designer",
          periodo: "6 months",
          stack: "Figma, Notion",
        },
        contexto: [
          "SIEG IriS is a SaaS product used by accounting firms to monitor and manage tax pendencies.",
          "After years of evolution, the system had accumulated visual inconsistencies, fragmented flows, and different interface patterns across modules, making the experience less intuitive and increasing the effort required for everyday tasks.",
          "Beyond a visual brand refresh, this was an opportunity to rethink the product experience more broadly, balancing user needs, business goals, and technical feasibility.",
        ],
        desafio: [
          "The challenge wasn't just modernizing the interface. We needed to reorganize complex flows, reduce users' cognitive load, and create a more consistent experience without disrupting the routine of professionals who relied on the system daily for tax processes.",
          "At the same time, the solution needed to establish reusable standards that would make future product evolution easier.",
        ],
        objetivos: [
          "Simplify critical navigation flows.",
          "Improve information organization.",
          "Reduce inconsistencies across different modules.",
          "Modernize the product's visual identity.",
          "Create a reusable foundation for future interface evolution.",
        ],
        problema: "Essential features were buried under unnecessary layers of information. This caused low system adoption and user frustration — the problem wasn't aesthetic, it was structural.",
        papel: [
          "Lead the Discovery process in partnership with Product.",
          "Map pain points and opportunities through user research.",
          "Structure new navigation flows.",
          "Redesign the interface with usability and consistency in mind.",
          "Build an initial component library in Figma to support interface standardization.",
          "Follow the evolution of the solutions throughout development.",
        ],
        discovery: [
          "Before proposing anything visual, we set out to understand how users were actually using the system and what their main difficulties were when completing tasks.",
          "Discovery was conducted through interviews, journey analysis, benchmarking, and organizing information using Card Sorting.",
          "This process surfaced the opportunities that guided every design decision throughout the project.",
        ],
        pesquisa: "User interviews, journey analysis, benchmarking, and Card Sorting to reorganize the system's information structure.",
        insights: [
          "Overly complex navigation for frequent tasks.",
          "A large volume of information competing for the user's attention.",
          "Inconsistency across components and visual patterns.",
          "Different flows for similar tasks.",
          "A steep learning curve for new users.",
        ],
        hipoteses: [
          "If we reorganized the menus and reduced how much information was shown at once, system usability would improve.",
          "If we applied visual consistency across the whole interface, that would increase users' perception of quality and trust in the system.",
        ],
        estrategia: [
          { titulo: "Simplify", descricao: "Cut steps and make key flows more direct." },
          { titulo: "Organize", descricao: "Improve information hierarchy to support decision-making." },
          { titulo: "Standardize", descricao: "Create reusable patterns that increased consistency across different areas of the product." },
          { titulo: "Prepare to scale", descricao: "Build a foundation that would let the interface evolve more efficiently over time." },
        ],
        tradeoffs: [{ titulo: "Modernization × Continuity of experience", descricao: "During the refactor, one of the main challenges was modernizing the interface without compromising users' familiarity with the product. We chose to preserve already-consolidated patterns in the most critical flows, while reorganizing the information architecture, visual hierarchy, and interface components. This decision allowed the experience to evolve gradually, reducing the learning curve and making the changes easier to adopt." }],
        decisoes: [],
        prototipacao: [
          "Building on what we learned in Discovery, we explored different navigation alternatives, information organization, and page structures.",
          "Wireframes let us validate hypotheses before moving into visual design, reducing rework and aligning expectations across Product, Design, and Engineering.",
        ],
        solucao: {
          intro: "The solution consisted of a complete reorganization of the architecture of the product's main screens. Key changes included:",
          itens: [
            "reorganizing the dashboards",
            "simplifying navigation",
            "revising the visual hierarchy",
            "standardizing components",
            "improving filters and tables",
            "greater clarity in how information was presented",
          ],
          fechamento: "The goal was to reduce users' cognitive load and make completing tasks more efficient.",
        },
        componentLibrary: [
          "During the project we noticed several interface elements were being recreated over and over, making maintenance harder and undermining the product's visual consistency.",
          "As an immediate response, we structured a component library in Figma, bringing together color, typography, button, input, icon, and other reusable element standards.",
          "While not yet a full Design System, this initiative marked an important step forward in Design maturity within the company. It let us validate patterns, reduce inconsistencies, and made clear the need to evolve toward a structured Design System — an initiative that would be developed later.",
          "This project was the first step toward building SIEG's official Design System.",
        ],
        colaboracao: "The project was developed in constant collaboration with Product and Engineering. Decisions were discussed throughout the process to balance user needs, business goals, and technical feasibility, reducing risk during implementation.",
        validacao: "",
        handoff: "",
        resultados: [
          "Simpler, more intuitive navigation.",
          "A visually more consistent interface.",
          "Better organization of information.",
          "Reduced complexity across flows.",
          "A reusable foundation for the product's continued evolution.",
          "Positive user feedback during the validations we ran.",
        ],
        resultadosNota: "Note: since we don't have consolidated quantitative metrics for this project, I chose to present only results that can be backed by real experience, rather than using unverified numbers.",
        aprendizados: [
          "This project reinforced that a refactor goes far beyond a visual update. By deeply understanding users' context and structuring decisions collaboratively, we were able to create a more consistent experience and prepare the product for future evolution.",
          "It was also during this project that we recognized the importance of standardizing components and creating a shared language between Design and Development — a learning that directly influenced the creation of the company's official Design System.",
        ],
        fechamento: "More than redesigning interfaces, this project marked a shift in how Design came to be thought of within the company. Building the component library made clear the need for a more scalable structure, serving as the starting point for the official Design System developed later on.",
        proximosPassos: ["Refactoring Íris made clear the need for more consistent standards between Design and Development. The component library built during the project became the foundation for building the DSI, SIEG's official Design System."],
        imagens: [
          { label: "Before the refactor", descricao: "Original Íris screen — overloaded menus and information", src: "images/iris-01-antes.png" },
          { label: "Research flowchart", descricao: "Research → Journey Mapping → Data Analysis → Benchmarking", src: "images/iris-02-fluxograma.png" },
          { label: "Íris Component Library", descricao: "Color palette, typography, and components (buttons, inputs, icons)", src: "images/iris-04-component-library.png" },
          { label: "Wireframes", descricao: "Low-fidelity structure validating the new navigation", src: "images/iris-03-wireframes.png" },
          { label: "After the refactor", descricao: "Final dashboard — the new SIEG Íris", src: "images/iris-05-depois.png" },
        ],
      },
    ],
  },
};

